Today's Update

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,7 +1,7 @@
 workflows:
   my-workflow:
     name: Tv 360
-    instance_type: windows_x2
+    instance_type: mac_pro
     max_build_duration: 120
     environment:
       groups:
@@ -22,13 +22,41 @@ workflows:
           source: true
       cancel_previous_builds: false
     scripts:
-      - ...
-      - echo "single line script"
-      - name: Flutter test
-        script: flutter test
-        ignore_failure: false
+      - name: Run iOS tests
+        script: |
+          set -e # exit on first failed command
+
+          xcode-project run-tests \
+              --workspace ${XCODE_WORKSPACE?} \
+              --scheme ${XCODE_SCHEME?} \
+              --device "iPhone 12"
+        test_report: build/ios/test/*.xml
+      - name: Add provisioning profiles
+        script: |
+          set -e # exit on first failed command
+
+          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
+          mkdir -p "$PROFILES_HOME"
+          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
+      - name: Add signing certificate
+        script: |
+          set -e # exit on first failed command
+
+          echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
+          keychain initialize
+          keychain add-certificates \
+              --certificate /tmp/certificate.p12 \
+              --certificate-password ${CERTIFICATE_PASSWORD?}
+      - name: Increment build number
+        script: agvtool new-version -all $BUILD_NUMBER
+      - name: Set up code signing settings on Xcode project
+        script: xcode-project use-profiles
+      - name: Build ipa for distribution
+        script: xcode-project build-ipa \
+                    --workspace "${XCODE_WORKSPACE?}" \
+                    --scheme "${XCODE_SCHEME?}"
     artifacts:
-      - build/**/outputs/bundle/**/*.aab
+      - build/ios/ipa/*.ipa
     publishing:
       email:
         recipients:
@@ -40,9 +68,6 @@ workflows:
         - name: Build iOS
           working_directory: mobile/ios
           script: pwd # current working directory is /Users/builder/clone/mobile/ios
-        - name: Build Android
-          working_directory: mobile/android
-          script: pwd # current working directory is /Users/builder/clone/mobile/android
         - name: Process Logs
           working_directory: /Users/builder/Library/Logs
           script: pwd # current working directory is /Users/builder/Library/Logs
